'use client';
import Link from 'next/link';
import {useState} from 'react';
import {Shield,ArrowUpRight,ArrowRight,BookOpen,Scale,Compass,MessageCircle,Home,Bookmark,Search,Menu,X,Sparkles,Heart,Check,LockKeyhole,GraduationCap,Briefcase,Globe,Users} from 'lucide-react';
import {provisions,topicNames,topicDescriptions,rightProvisions,scenarios,organizations,disclaimer} from '@/data/catalog';
import {LawCard,PageTitle,Back,Sources,Empty,Emergency,Notice,ruleNames} from './shared';
import {Button} from './ui/button';
import {searchProvisions} from '@/lib/legal/matcher';
import {PrivacyPage} from './privacy';
import {Wizard,ResultPage,Advisor,SavedPage,DemoPage} from './help';
const nav=[['/','Нүүр',Home],['/rights','Миний эрх',Shield],['/laws','Хууль',Scale],['/help','Тусламж',Compass],['/advisor','AI зөвлөх',MessageCircle],['/saved','Миний мэдээлэл',Bookmark]] as const;
const topicIcons=[Users,Shield,LockKeyhole,GraduationCap,Briefcase,MessageCircle,Heart,Globe,Heart,Scale,Users];
export default function App({path,query={}}:{path:string;query?:Record<string,string|string[]|undefined>}){
 const [menu,setMenu]=useState(false);
 let content:React.ReactNode;
 if(path==='/')content=<HomePage/>;
 else if(path==='/laws'||path==='/search')content=<Library global={path==='/search'}/>;
 else if(path.startsWith('/laws/'))content=<LawDetail id={path.split('/')[2]}/>;
 else if(path==='/rights')content=<Rights/>;
 else if(path.startsWith('/rights/'))content=<RightDetail id={path.split('/')[2]}/>;
 else if(path==='/help')content=<Wizard/>;
 else if(path==='/help/result')content=<ResultPage scenarioId={typeof query.scenario==='string'?query.scenario:undefined} planId={typeof query.plan==='string'?query.plan:undefined}/>;
 else if(path==='/advisor')content=<Advisor/>;
 else if(path==='/organizations')content=<Directory/>;
 else if(path==='/guides/nhrc-complaint')content=<ComplaintGuide/>;
 else if(path==='/privacy')content=<PrivacyPage/>;
 else if(path==='/saved')content=<SavedPage/>;
 else if(path==='/demo')content=<DemoPage/>;
 else if(path==='/safety')content=<><PageTitle eyebrow="АЮУЛГҮЙ БАЙДАЛ" title="Та ганцаараа биш." description="Шууд аюул тулгарсан бол цахим зөвлөхийн хариуг хүлээлгүй тусламж хүсээрэй."/><Emergency child/><Link prefetch={false} href="/organizations" className="button button-secondary">Байгууллагуудыг харах</Link></>;
 else content=<Empty title="Хуудас олдсонгүй" description="Хаягаа шалгаад нүүр хуудас руу буцна уу."><Link prefetch={false} href="/">Нүүр рүү буцах</Link></Empty>;
 return <><a className="skip-link" href="#main">Үндсэн агуулга руу</a><header className="site-header"><div className="shell header-inner"><Link prefetch={false} href="/" className="brand" aria-label="HURMUST нүүр"><span><Shield size={22}/></span>HURMUST<span className="brand-dot">.</span></Link><nav className="desktop-nav" aria-label="Үндсэн цэс">{nav.map(([href,label])=><Link prefetch={false} key={href} href={href} className={href==='/saved'?'account-nav':undefined} aria-current={path===href?'page':undefined}>{label}</Link>)}</nav><div className="header-actions"><Link prefetch={false} href="/search" className="icon-link" aria-label="Хайх"><Search size={19}/></Link><Link prefetch={false} href="/saved" className="icon-link" aria-label="Хадгалсан мэдээлэл"><Bookmark size={19}/></Link><Link prefetch={false} href="/help" className="button button-primary header-cta">Тусламж авах<ArrowUpRight size={16}/></Link><Button variant="ghost" className="menu-toggle icon-button" aria-expanded={menu} aria-label={menu?'Цэс хаах':'Цэс нээх'} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</Button></div></div>{menu&&<nav className="mobile-menu" aria-label="Нэмэлт цэс">{[...nav.map(([href,label])=>[href,label]),['/organizations','Байгууллагууд'],['/guides/nhrc-complaint','ХЭҮК-т гомдол гаргах'],['/demo','Жишээ нөхцөл']].map(([href,label])=><Link prefetch={false} key={href} href={href} onClick={()=>setMenu(false)}>{label}</Link>)}</nav>}</header>
 <main id="main" className="shell main">{content}</main><footer className="site-footer"><div className="shell footer-grid"><div><Link prefetch={false} href="/" className="brand">HURMUST<span className="brand-dot">.</span></Link><p>Эрхээ ойлгох эхний алхам.</p><small>Туршилтын хувилбар · {disclaimer}</small></div><div className="footer-links"><Link prefetch={false} href="/organizations">Хаана хандах вэ?</Link><Link prefetch={false} href="/guides/nhrc-complaint">Гомдол гаргах заавар</Link><Link prefetch={false} href="/saved">Миний мэдээлэл</Link><Link prefetch={false} href="/safety">Яаралтай тусламж</Link><Link prefetch={false} href="/privacy">Нууцлал ба хадгалалт</Link></div></div><div className="shell footer-bottom"><span>© 2026 HURMUST</span><span>Хуулийн эх сурвалж: <a href="https://legalinfo.mn" target="_blank" rel="noopener noreferrer">Legalinfo.mn ↗</a></span><span>Ноорог төхөөрөмж дээр хадгалагдана. Үүлэн хадгалалт тусдаа зөвшөөрөлтэй.</span></div></footer>
 <nav className="bottom-nav" aria-label="Гар утасны цэс">{nav.map(([href,label,Icon])=><Link prefetch={false} key={href} href={href} className={href==='/saved'?'account-nav':undefined} aria-current={path===href?'page':undefined}><Icon size={20}/><span>{label==='Миний эрх'?'Эрх':label==='AI зөвлөх'?'AI':label==='Миний мэдээлэл'?'Мэдээлэл':label}</span></Link>)}</nav></>;
}
function HomePage(){return <><section className="hero"><div className="hero-copy"><span className="eyebrow"><i/>ЭРХЭЭ ОЙЛГОХ ЭХНИЙ АЛХАМ</span><h1>Эрхээ мэд.<br/><span>Зөв алхмаа ол.</span></h1><p>Танд тохиолдсон асуудал ямар эрх, ямар хуультай холбоотой байж болохыг ойлгож, дараагийн алхмаа олоход тусална.</p><div className="hero-buttons"><Link prefetch={false} href="/help" className="button button-primary">Тусламж авах <ArrowUpRight size={20}/></Link><Link prefetch={false} href="/rights" className="button button-secondary">Эрхээ мэдэх <ArrowRight size={18}/></Link></div><div className="hero-assurance"><span><LockKeyhole size={15}/>Бүртгэл шаардлагагүй</span><span><Check size={15}/>Албан ёсны хуулийн эх сурвалж</span></div></div>
 <div className="hero-art"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="hero-note"><div className="hero-note-header"><span className="status-dot"/>ТАНЫ ЭРХ, ТАНЫ ДУУ ХООЛОЙ<Shield size={24}/></div><div className="hero-emblem"><Shield size={70} strokeWidth={1}/><Heart className="emblem-heart" size={24} strokeWidth={1.4}/></div><h2>Хүндлэл хүн бүрт.</h2><p>Юу болсныг ойлгоё.<br/>Хуулиас замаа олъё.</p><div className="path-preview"><span>Асуудал</span><ArrowRight size={15}/><span>Эрх</span><ArrowRight size={15}/><span>Хууль</span><ArrowRight size={15}/><span>Алхам</span></div><Link prefetch={false} href="/demo" className="hero-note-link">Жишээгээр үзэх<ArrowUpRight size={18}/></Link></div><div className="floating-citation"><div className="citation-icon"><Scale size={22}/></div><div><strong>БОЛОВСРОЛЫН ЕРӨНХИЙ ХУУЛЬ</strong><p>10.2.6 · Бусдыг дарамтлахгүй байх үүрэг</p></div><Check size={18}/></div></div></section>
 <section className="trust-strip"><span><Scale size={19}/>{provisions.length} шалгасан заалт</span><span><BookOpen size={19}/>10 хуулийн эх сурвалж</span><span><Shield size={19}/>Энгийн, ойлгомжтой тайлбар</span><Link prefetch={false} href="/laws">Хуулийн сантай танилцах<ArrowUpRight size={17}/></Link></section>
 <section className="section"><div className="section-heading"><div><span className="eyebrow">ТАНД ЮУ ХЭРЭГТЭЙ ВЭ?</span><h2>Эндээс эхэлж болно.</h2></div><p>Том асуудлыг жижиг, ойлгомжтой алхамд хуваая.</p></div><div className="quick-grid">{[['Миний эрх зөрчигдсөн байж магадгүй','Болсон явдлаа тайлбарлаж, боломжит алхмаа харах','/help',Compass],['Ямар хууль хамаарахыг мэдмээр байна','Эрх, үүрэг, заалтыг энгийнээр ойлгох','/laws',Scale],['Хаана хандахаа мэдэхгүй байна','Таны асуудалд тохирох байгууллагыг олох','/organizations',Globe],['Хүний эрхээ судалмаар байна','Өдөр тутмын жишээгээр эрхээ таних','/rights',BookOpen]].map(([title,desc,href,Icon])=>{const I=Icon as typeof Compass;return <Link prefetch={false} href={href as string} key={title as string} className="quick-card"><div><I size={25}/><ArrowUpRight size={18}/></div><h3>{title as string}</h3><p>{desc as string}</p></Link>;})}</div></section>
 <section className="section rights-preview"><div className="section-heading"><div><span className="eyebrow">МИНИЙ ЭРХ</span><h2>Эрх тань амьдралын бүх орчинд.</h2></div><Link prefetch={false} href="/rights" className="text-link">Бүх эрхийг харах<ArrowUpRight size={17}/></Link></div><div className="topic-grid">{['education','work','privacy','safety'].map((id,i)=>{const Icon=[GraduationCap,Briefcase,LockKeyhole,Shield][i];return <Link prefetch={false} href={`/rights/${id}`} key={id} className="topic-card"><Icon size={27}/><h3>{topicNames[id]}</h3><span>{rightProvisions(id).length} холбогдох заалт<ArrowUpRight size={17}/></span></Link>;})}</div></section>
 <section className="how-section"><div><span className="eyebrow">ХЭРХЭН ТУСЛАХ ВЭ?</span><h2>Өөрийгөө буруутгахаас өмнө,<br/>эрхээ ойлгоорой.</h2><p>HURMUST нь шүүх, хуульчийг орлохгүй. Харин зөв асуулт асууж, эхний алхмаа хийхэд тань тусална.</p><Link prefetch={false} href="/help" className="button button-primary">Өөрийн нөхцөлөө шалгах<ArrowUpRight size={18}/></Link></div><ol>{[['Юу болсныг тайлбарла','Өөрийн үгээр бичээрэй. Хувийн нэр, регистр оруулах шаардлагагүй.'],['Эрх, хууль, үүргээ ойлго','Холбогдож болох заалтуудыг эх сурвалжтай нь үзээрэй.'],['Дараагийн алхмаа сонго','Баримтаа бэлдэж, тохирох байгууллагад хандах замаа ол.']].map(([t,d],i)=><li key={t}><span>0{i+1}</span><div><h3>{t}</h3><p>{d}</p></div></li>)}</ol></section>
 <aside className="safety-banner"><Shield size={21}/><div><strong>Яг одоо аюултай нөхцөлд байна уу?</strong><p>Цагдаа 102 · Хүүхдийн тусламж 108 · Түргэн тусламж 103</p></div><Link prefetch={false} href="/safety">Яаралтай тусламж<ArrowUpRight size={17}/></Link></aside></>;}
function Library({global=false}:{global?:boolean}){
 const [query,setQuery]=useState('');const [filter,setFilter]=useState('');const [law,setLaw]=useState('');
 const laws=[...new Map(provisions.map(p=>[p.lawId,p.lawName])).entries()];
 const filters=[['RIGHT','Миний эрх'],['own','Миний үүрэг'],['others','Бусдын үүрэг'],['PROHIBITION','Хориглосон үйлдэл'],['PROCEDURE','Гомдол гаргах'],['children','Хүүхэд'],['education','Сургууль'],['work','Ажил'],['privacy','Хувийн мэдээлэл'],['violence','Хүчирхийлэл'],['online','Онлайн орчин']];
 const results=searchProvisions(query).filter(p=>(!law||p.lawId===law)&&(!filter||p.ruleType===filter||(filter==='own'&&p.ruleType==='DUTY'&&p.whoHasTheDuty?.some(x=>['Иргэн','Суралцагч'].includes(x)))||(filter==='others'&&p.ruleType==='DUTY'&&!p.whoHasTheDuty?.some(x=>['Иргэн','Суралцагч'].includes(x)))||p.relatedTopics.includes(filter==='online'?'privacy':filter)));
 const rights=Object.entries(topicNames).filter(([id,name])=>!query||`${name} ${topicDescriptions[id]}`.includes(query)||rightProvisions(id).some(p=>results.some(r=>r.id===p.id)));
 return <><PageTitle eyebrow={global?'НЭГДСЭН ХАЙЛТ':'ХУУЛИЙН САН'} title={global?'Асуултаас эх сурвалж руу.':'Эрхээ хуулиас ойлгоё'} description="Монгол Улсын хууль тогтоомжийн хүний эрхтэй холбоотой зүйл, заалтыг энгийн тайлбартайгаар хараарай."/><div className="search-row"><label className="search-box"><Search size={21}/><span className="sr-only">Хууль, эрх, асуудлаар хайх</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Хууль, эрх, асуудлаар хайх..."/>{query&&<Button variant="ghost" onClick={()=>setQuery('')} aria-label="Хайлтыг цэвэрлэх"><X size={17}/></Button>}</label><select aria-label="Хуулиар шүүх" value={law} onChange={e=>setLaw(e.target.value)}><option value="">Бүх хууль</option>{laws.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></div><div className="chips"><Button variant={!filter?'default':'secondary'} onClick={()=>setFilter('')}>Бүгд</Button>{filters.map(([id,label])=><Button key={id} variant={filter===id?'default':'secondary'} onClick={()=>setFilter(filter===id?'':id)} aria-pressed={filter===id}>{label}</Button>)}</div>
 {global&&<><h2 className="subheading">Холбоотой эрх</h2><div className="tags rights-tags">{rights.map(([id,label])=><Link prefetch={false} key={id} href={`/rights/${id}`}>{label}<ArrowUpRight size={15}/></Link>)}</div><Link prefetch={false} className="guide-link" href="/guides/nhrc-complaint">Гомдол гаргах заавар · ХЭҮК<ArrowUpRight size={17}/></Link><h2 className="subheading">Холбогдох хууль</h2></>}
 <div className="results-meta" role="status"><span>{results.length} заалт олдлоо</span><span>Эх сурвалж: Legalinfo · Шалгасан: 2026-10-06</span></div>{results.length?<div className="law-grid">{results.map(p=><LawCard key={p.id} provision={p}/>)}</div>:<Empty/>}<Notice/></>;
}
function LawDetail({id}:{id:string}){const p=provisions.find(p=>p.id===id);if(!p)return <Empty title="Заалт олдсонгүй"/>;return <><Back/><PageTitle eyebrow={p.lawName} title={p.referenceLabel} description={ruleNames[p.ruleType]}/><div className="detail-layout"><article className="detail-main"><span className="tag">HURMUST-ийн хялбаршуулсан тайлбар</span><h2>Энгийнээр тайлбарлавал</h2><p className="large-text">{p.plainLanguageSummary}</p><h2>Хуулийн заалт</h2><blockquote>{p.officialTextShort}</blockquote><small>Албан ёсны эхээс авсан товчилсон эшлэл. Бүрэн нөхцөл, тайлбарыг эх сурвалжаас уншаарай.</small><h2>Хэнд хамаарах вэ?</h2><p>{p.childOnly?'18 нас хүрээгүй хүүхэд болон хүүхэд хамгаалах үүрэг бүхий этгээд.':p.contexts?.length?`${p.contexts.map(c=>({school:'Сургууль',university:'Их сургууль',work:'Ажлын байр',home:'Гэр бүл'}[c]??c)).join(', ')} орчны харилцаанд хамаарна.`:'Заалтын үйлчлэх хүрээнд байгаа хүн, байгууллага. Хуулийн нөхцөлүүдийг давхар шалгана.'}</p><h2>Ямар үүрэг / эрх вэ?</h2><p>{ruleNames[p.ruleType]}{p.whoHasTheDuty?.length?` · ${p.whoHasTheDuty.join(', ')}`:''}</p><h2>Ямар нөхцөлд хэрэг болох вэ?</h2><p>{p.relatedTopics.map(t=>topicNames[t]).join(', ')}-тай холбоотой нөхцөл байдлыг ойлгох үед. Энэ заалт таны хэрэгт автоматаар хэрэглэгдэнэ гэсэн үг биш.</p><h2>Жишээ</h2><p>Сургуулийн дарамт, ажлын харилцаа, хувийн зураг тараасан зэрэг асуудлыг тайлбарлахдаа нөхцөл, нас, орчноо тусад нь шалгана. Доорх жишээнээс тохирохыг сонгон туршиж болно.</p><Link prefetch={false} href="/demo" className="button button-secondary">Жишээ нөхцөлөөр үзэх<ArrowUpRight size={17}/></Link><Notice/><Sources p={p}/></article><aside className="detail-aside"><LawCard provision={p}/><div className="aside-note"><h3>Дараагийн алхмаа олох</h3><p>Танд тохиолдсон асуудлыг өөрийн үгээр тайлбарлаарай.</p><Link prefetch={false} href="/help" className="button button-primary">Тусламж авах<ArrowUpRight size={16}/></Link></div></aside></div><h2 className="subheading">Холбоотой зүйл, заалт</h2><div className="law-grid">{provisions.filter(x=>x.id!==p.id&&x.lawId===p.lawId).slice(0,3).map(x=><LawCard key={x.id} provision={x}/>)}</div></>;}
function Rights(){return <><PageTitle eyebrow="МИНИЙ ЭРХ" title="Эрхээ мэдэх нь өөрийгөө хамгаалах эхлэл." description="Өдөр тутмын амьдралд хамаарах эрхүүдийг энгийн тайлбар, хуулийн эх сурвалжтай нь танилцаарай."/><div className="topic-grid rights-grid">{Object.entries(topicNames).map(([id,label],i)=>{const Icon=topicIcons[i];return <Link prefetch={false} href={`/rights/${id}`} key={id} className="topic-card"><Icon size={28}/><h2>{label}</h2><p>{topicDescriptions[id]}</p><span>{rightProvisions(id).length} холбогдох заалт<ArrowUpRight size={19}/></span></Link>;})}</div></>;}
function RightDetail({id}:{id:string}){if(!topicNames[id])return <Empty title="Эрх олдсонгүй"/>;const related=rightProvisions(id);return <><Back href="/rights">Эрхийн сан руу</Back><PageTitle eyebrow="МИНИЙ ЭРХ" title={topicNames[id]} description={topicDescriptions[id]}/><div className="info-grid"><article><h2>Энэ эрх юу вэ?</h2><p>{topicDescriptions[id]}</p></article><article><h2>Энгийн жишээ</h2><p>{id==='work'?scenarios[2].description:id==='privacy'||id==='online'?scenarios[1].description:scenarios[3].description}</p></article><article><h2>Ямар үед зөрчигдөж болох вэ?</h2><p>Дарамт, зөвшөөрөлгүй мэдээлэл ашиглах, ялгаварлан харьцах зэрэг үйлдэл байж болно. Нөхцөл байдлыг холбогдох хууль, баримтаар шалгана.</p></article></div><h2 className="subheading">Холбогдох хуулийн заалт</h2><div className="law-grid">{related.filter(p=>p.ruleType!=='DUTY').slice(0,6).map(p=><LawCard key={p.id} provision={p}/>)}</div><h2 className="subheading">Хэн ямар үүрэгтэй вэ?</h2><div className="law-grid">{related.filter(p=>p.ruleType==='DUTY').slice(0,4).map(p=><LawCard key={p.id} provision={p}/>)}</div>{!related.some(p=>p.ruleType==='DUTY')&&<p>Энэ сэдэвт тусгай үүргийн баталгаажсан заалт одоогоор сонгоогүй. Холбогдох хуулийн эхийг шалгана уу.</p>}<div className="callout"><h2>Би юу хийж болох вэ?</h2><p>Аюулгүй байдлаа анхаарч, болсон явдлын огноо, баримтыг хадгалан, боломжит алхмаа шалгаарай.</p><Link prefetch={false} href="/help" className="button button-primary">Алхмаа олох<ArrowUpRight size={17}/></Link><Link prefetch={false} href="/organizations" className="button button-secondary">Хаана хандах вэ?</Link></div><Notice/></>;}
export function Directory({topics}:{topics?:string[]}){const [filter,setFilter]=useState('');const items=organizations.filter(o=>(!filter||o.services.includes(filter))&&(!topics||o.services.some(s=>topics.includes(s))));return <><PageTitle eyebrow="ТУСЛАМЖИЙН ЗАМ" title="Хаана хандаж болох вэ?" description="Асуудалдаа тохирох байгууллага, тусламжийн сувгийг сонгоорой. Хандахаас өмнө албан ёсны мэдээллийг давхар шалгана уу."/><label className="directory-filter">Асуудлын төрөл<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Бүгд</option>{Object.entries(topicNames).filter(([id])=>!['online','discrimination'].includes(id)).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><div className="organization-grid">{items.map(o=><article key={o.id} className="organization-card"><div className="org-top"><span className={o.emergency?'tag urgent':'tag'}>{o.type}</span>{o.verified?<Check size={19}/>:<span className="unverified">Баталгаажуулаагүй</span>}</div><h2>{o.name}</h2><p>{o.services.map(s=>topicNames[s]).join(' · ')}</p>{o.phone&&<a className="phone-number" href={`tel:${o.phone.replace(/-/g,'')}`}>{o.phone}<ArrowUpRight size={18}/></a>}<dl><dt>Хаяг, ажиллах цаг</dt><dd>Албан ёсны сувгаар тодруулна уу.</dd>{o.email&&<><dt>Цахим шуудан</dt><dd><a href={`mailto:${o.email}`}>{o.email}</a></dd></>}</dl>{o.website&&<a className="text-link" href={o.website} target="_blank" rel="noopener noreferrer">Албан ёсны сайт<ArrowUpRight size={17}/></a>}{o.source&&<a className="small-link" href={o.source} target="_blank" rel="noopener noreferrer">Холбоо барих мэдээллийн эх сурвалж · {o.lastVerified}</a>}{!o.verified&&<p className="small-text">Танай байгууллагын холбоо барих мэдээлэл баталгаажуулаагүй. Дугаар зохиож оруулаагүй.</p>}</article>)}</div>{!items.length&&<Empty/>}</>;}
function ComplaintGuide(){const refs=['20.1','20.2','20.3','20.6','21.1','21.3','22.1.1','22.1.2','22.1.3','22.1.4','23.1','23.2','23.3','24.1.2','26.1.1'];return <><Back href="/organizations">Байгууллагууд руу</Back><PageTitle eyebrow="АЛХАМТ ЗААВАР" title="ХЭҮК-т гомдол гаргах" description="Гомдол гаргах эрх, хэлбэр, бүрдүүлэх мэдээлэл, хугацааг хуулийн заалттай нь танилцаарай."/><div className="callout"><h2>Эндээс гомдол илгээхгүй.</h2><p>HURMUST нь бэлтгэлээ хангахад тусална. Гомдлоо Комиссын албан ёсны сувгаар гаргана.</p><a className="button button-primary" href="https://2026.nhrcm.gov.mn/complaint" target="_blank" rel="noopener noreferrer">ХЭҮК-ийн албан ёсны суваг<ArrowUpRight size={17}/></a></div>{[['Хэн гомдол гаргаж болох вэ?',refs.slice(0,4)],['Ямар хэлбэрээр гаргах вэ?',refs.slice(4,6)],['Гомдолд юу бичиж, юу хавсаргах вэ?',refs.slice(6,10)],['Хугацаа ба шийдвэрлэлт',refs.slice(10,13)],['Ямар шаардлага үйлчлэх вэ?',refs.slice(13)]].map(([title,list])=><section key={title as string} className="section"><h2>{title as string}</h2><div className="law-grid">{(list as string[]).map(ref=>provisions.find(p=>p.lawId==='nhrc'&&p.referenceLabel===ref)).filter(p=>!!p).map(p=><LawCard key={p.id} provision={p}/>)}</div></section>)}<p className="notice">Гомдол хүлээн авах хязгаарлалт болон Комиссын бүрэн эрхийг доорх заалтаас уншина уу.</p><div className="law-grid">{provisions.filter(p=>p.lawId==='nhrc'&&['22.2','25.1.4'].includes(p.referenceLabel)).map(p=><LawCard key={p.id} provision={p}/>)}</div><a className="text-link" href="https://legalinfo.mn/mn/detail?lawId=15152" target="_blank" rel="noopener noreferrer">Хуулийн албан ёсны эх<ArrowUpRight size={17}/></a><Notice/></>;}
